### PR TITLE
Fat docker container and automatic system dependencies

### PR DESCRIPTION
**Pull request by bertsky**
- add Dockerfile which builds selected modules/executables for container installation
- encapsulate all modules' system requirements (both for local and container setup)
- post-installation fixes for conflicting requirements
- add `workflow-configuration` module

### CODE REVIEW

**Comment by bertsky** [comment]
@stweil, giving up after you made too many incompatible and unfounded changes, despite my explanation in the comments.

**Comment by stweil** [comment]
If you want, I can rebase your branch and fix the few merge conflicts.

**Comment by bertsky** [comment]
> If you want, I can rebase your branch and fix the few merge conflicts.

Please do. (The branch of stweil/ocrd_all#6 should allow edits.)

**Comment by bertsky** [comment]
> > If you want, I can rebase your branch and fix the few merge conflicts.
> 
> Please do. (The branch of stweil#6 should allow edits.)

Or rather, do everything in one merge commit (without rebasing)?

**Pull request merged**
